<?php

return array (
  0 => 
  array (
    'user_id' => 1,
    'address' => '221b Baker Street',
    'city' => 'London',
    'country' => 'United Kingdom',
    'square_meters' => 120,
    'bathrooms' => 2,
    'rooms' => 3,
    'price' => 1500.0,
    'discount' => 0,
    'latitude' => 51.52,
    'longitude' => -0.15,
    'cover_image' => 'london_house.jpg',
    'description' => 'A beautiful apartment in the heart of London',
  ),
  1 => 
  array (
    'user_id' => 2,
    'address' => '5 Rue de la Paix',
    'city' => 'Paris',
    'country' => 'France',
    'square_meters' => 100,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 0,
    'latitude' => 48.86,
    'longitude' => 2.33,
    'cover_image' => 'paris_apartment.jpg',
    'description' => 'A charming apartment in the center of Paris',
  ),
  2 => 
  array (
    'user_id' => 3,
    'address' => 'Via dei Condotti 91',
    'city' => 'Rome',
    'country' => 'Italy',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1100.0,
    'discount' => 10,
    'latitude' => 41.9,
    'longitude' => 12.5,
    'cover_image' => 'rome_apartment.jpg',
    'description' => 'Cozy apartment in the historical center of Rome',
  ),
  3 => 
  array (
    'user_id' => 4,
    'address' => 'Königinstraße 23',
    'city' => 'Berlin',
    'country' => 'Germany',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 900.0,
    'discount' => 0,
    'latitude' => 52.51,
    'longitude' => 13.41,
    'cover_image' => 'berlin_apartment.jpg',
    'description' => 'Modern apartment in the vibrant city of Berlin',
  ),
  4 => 
  array (
    'user_id' => 4,
    'address' => 'Carrer d\'Aragó, 514',
    'city' => 'Barcelona',
    'country' => 'Spain',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 10,
    'latitude' => 41.3981,
    'longitude' => 2.1902,
    'cover_image' => 'barcelona_apartment.jpg',
    'description' => 'Bright apartment in central Barcelona',
  ),
  5 => 
  array (
    'user_id' => 5,
    'address' => 'Lindengasse 41',
    'city' => 'Vienna',
    'country' => 'Austria',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1100.0,
    'discount' => 0,
    'latitude' => 48.2028,
    'longitude' => 16.3501,
    'cover_image' => 'vienna_apartment.jpg',
    'description' => 'Comfortable apartment in vibrant Neubau district',
  ),
  6 => 
  array (
    'user_id' => 6,
    'address' => 'Ulitsa Kuznetskiy Most, 21',
    'city' => 'Moscow',
    'country' => 'Russia',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 1300.0,
    'discount' => 0,
    'latitude' => 55.7619,
    'longitude' => 37.6094,
    'cover_image' => 'moscow_apartment.jpg',
    'description' => 'Spacious apartment in the heart of Moscow',
  ),
  7 => 
  array (
    'user_id' => 7,
    'address' => 'Pikk 59',
    'city' => 'Tallinn',
    'country' => 'Estonia',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 59.4392,
    'longitude' => 24.7454,
    'cover_image' => 'tallinn_apartment.jpg',
    'description' => 'Historic apartment in Tallinn\'s Old Town',
  ),
  8 => 
  array (
    'user_id' => 8,
    'address' => 'Rue de la Régence 67',
    'city' => 'Brussels',
    'country' => 'Belgium',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 0,
    'latitude' => 50.842,
    'longitude' => 4.3583,
    'cover_image' => 'brussels_apartment.jpg',
    'description' => 'Central apartment near Brussels\' museums',
  ),
  9 => 
  array (
    'user_id' => 9,
    'address' => 'Storgata 53',
    'city' => 'Oslo',
    'country' => 'Norway',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1600.0,
    'discount' => 0,
    'latitude' => 59.9141,
    'longitude' => 10.7491,
    'cover_image' => 'oslo_apartment.jpg',
    'description' => 'Modern apartment in downtown Oslo',
  ),
  10 => 
  array (
    'user_id' => 10,
    'address' => 'Rue du Marché aux Herbes 112',
    'city' => 'Luxembourg',
    'country' => 'Luxembourg',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 0,
    'latitude' => 49.6106,
    'longitude' => 6.132,
    'cover_image' => 'luxembourg_apartment.jpg',
    'description' => 'Charming apartment in the heart of Luxembourg',
  ),
  11 => 
  array (
    'user_id' => 11,
    'address' => 'Freta 41/43',
    'city' => 'Warsaw',
    'country' => 'Poland',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 900.0,
    'discount' => 0,
    'latitude' => 52.25,
    'longitude' => 21.0122,
    'cover_image' => 'warsaw_apartment.jpg',
    'description' => 'Comfortable apartment in historic Warsaw',
  ),
  12 => 
  array (
    'user_id' => 12,
    'address' => 'Długa 72',
    'city' => 'Gdańsk',
    'country' => 'Poland',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 54.352,
    'longitude' => 18.6466,
    'cover_image' => 'gdansk_apartment.jpg',
    'description' => 'Charming apartment in Gdańsk\'s Old Town',
  ),
  13 => 
  array (
    'user_id' => 13,
    'address' => 'Valdemāra iela 37',
    'city' => 'Riga',
    'country' => 'Latvia',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 700.0,
    'discount' => 0,
    'latitude' => 56.9496,
    'longitude' => 24.1052,
    'cover_image' => 'riga_apartment.jpg',
    'description' => 'Cozy apartment near Riga\'s parks',
  ),
  14 => 
  array (
    'user_id' => 14,
    'address' => 'Glockengießerwall 3',
    'city' => 'Hamburg',
    'country' => 'Germany',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 10,
    'latitude' => 53.5511,
    'longitude' => 9.9937,
    'cover_image' => 'hamburg_apartment.jpg',
    'description' => 'Cozy apartment in central Hamburg',
  ),
  15 => 
  array (
    'user_id' => 15,
    'address' => 'Strøget 15',
    'city' => 'Copenhagen',
    'country' => 'Denmark',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 0,
    'latitude' => 55.6761,
    'longitude' => 12.5683,
    'cover_image' => 'copenhagen_apartment.jpg',
    'description' => 'Lovely apartment in the heart of Copenhagen',
  ),
  16 => 
  array (
    'user_id' => 16,
    'address' => 'Piața Unirii 1',
    'city' => 'Bucharest',
    'country' => 'Romania',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 1000.0,
    'discount' => 0,
    'latitude' => 44.4268,
    'longitude' => 26.1025,
    'cover_image' => 'bucharest_apartment.jpg',
    'description' => 'Spacious apartment in the heart of Bucharest',
  ),
  17 => 
  array (
    'user_id' => 17,
    'address' => 'Ulitsa Dostoyevskogo 19',
    'city' => 'Saint Petersburg',
    'country' => 'Russia',
    'square_meters' => 95,
    'bathrooms' => 2,
    'rooms' => 3,
    'price' => 1100.0,
    'discount' => 0,
    'latitude' => 59.9386,
    'longitude' => 30.3141,
    'cover_image' => 'saintpetersburg_apartment.jpg',
    'description' => 'Bright apartment in Dostoyevsky\'s neighborhood',
  ),
  18 => 
  array (
    'user_id' => 18,
    'address' => 'Sıraselviler Cd. 39',
    'city' => 'Istanbul',
    'country' => 'Turkey',
    'square_meters' => 100,
    'bathrooms' => 2,
    'rooms' => 3,
    'price' => 900.0,
    'discount' => 10,
    'latitude' => 41.0082,
    'longitude' => 28.9784,
    'cover_image' => 'istanbul_apartment.jpg',
    'description' => 'Charming apartment in central Istanbul',
  ),
  19 => 
  array (
    'user_id' => 19,
    'address' => 'Knez Mihailova 30',
    'city' => 'Belgrade',
    'country' => 'Serbia',
    'square_meters' => 90,
    'bathrooms' => 2,
    'rooms' => 2,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 44.7866,
    'longitude' => 20.4489,
    'cover_image' => 'belgrade_apartment.jpg',
    'description' => 'Stylish apartment in downtown Belgrade',
  ),
  20 => 
  array (
    'user_id' => 20,
    'address' => 'Rue de la Croix d\'Or 10',
    'city' => 'Geneva',
    'country' => 'Switzerland',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2200.0,
    'discount' => 10,
    'latitude' => 46.2044,
    'longitude' => 6.1432,
    'cover_image' => 'geneva_apartment.jpg',
    'description' => 'Cozy apartment in central Geneva',
  ),
  21 => 
  array (
    'user_id' => 21,
    'address' => 'Rue du Mont-Blanc 17',
    'city' => 'Geneva',
    'country' => 'Switzerland',
    'square_meters' => 80,
    'bathrooms' => 2,
    'rooms' => 3,
    'price' => 2300.0,
    'discount' => 0,
    'latitude' => 46.2044,
    'longitude' => 6.1432,
    'cover_image' => 'geneva2_apartment.jpg',
    'description' => 'Modern apartment with a view of Mont Blanc',
  ),
  22 => 
  array (
    'user_id' => 22,
    'address' => 'Vesterbrogade 3B',
    'city' => 'Copenhagen',
    'country' => 'Denmark',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 0,
    'latitude' => 55.6761,
    'longitude' => 12.5683,
    'cover_image' => 'copenhagen2_apartment.jpg',
    'description' => 'Charming apartment in Vesterbro district',
  ),
  23 => 
  array (
    'user_id' => 23,
    'address' => 'Strada Ion Câmpineanu 20',
    'city' => 'Bucharest',
    'country' => 'Romania',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 900.0,
    'discount' => 0,
    'latitude' => 44.4268,
    'longitude' => 26.1025,
    'cover_image' => 'bucharest2_apartment.jpg',
    'description' => 'Comfortable apartment in central Bucharest',
  ),
  24 => 
  array (
    'user_id' => 24,
    'address' => 'Oxford Street 75',
    'city' => 'London',
    'country' => 'United Kingdom',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2400.0,
    'discount' => 10,
    'latitude' => 51.5145,
    'longitude' => -0.1557,
    'cover_image' => 'london_apartment.jpg',
    'description' => 'Luxury apartment in central London',
  ),
  25 => 
  array (
    'user_id' => 25,
    'address' => 'Corso Vittorio Emanuele II 90',
    'city' => 'Rome',
    'country' => 'Italy',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 0,
    'latitude' => 41.9028,
    'longitude' => 12.4964,
    'cover_image' => 'rome_apartment.jpg',
    'description' => 'Elegant apartment in the heart of Rome',
  ),
  26 => 
  array (
    'user_id' => 26,
    'address' => 'Marathonos 32',
    'city' => 'Athens',
    'country' => 'Greece',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 1000.0,
    'discount' => 0,
    'latitude' => 37.9838,
    'longitude' => 23.7275,
    'cover_image' => 'athens_apartment.jpg',
    'description' => 'Spacious apartment in central Athens',
  ),
  27 => 
  array (
    'user_id' => 27,
    'address' => 'Rue de la Loi/Wetstraat 100',
    'city' => 'Brussels',
    'country' => 'Belgium',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 0,
    'latitude' => 50.8503,
    'longitude' => 4.3517,
    'cover_image' => 'brussels_apartment.jpg',
    'description' => 'Modern apartment near European Quarter',
  ),
  28 => 
  array (
    'user_id' => 28,
    'address' => 'Lange Gasse 20',
    'city' => 'Vienna',
    'country' => 'Austria',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 10,
    'latitude' => 48.21,
    'longitude' => 16.3635,
    'cover_image' => 'vienna_apartment.jpg',
    'description' => 'Charming apartment in old Vienna',
  ),
  29 => 
  array (
    'user_id' => 29,
    'address' => 'Rua Augusta 180',
    'city' => 'Lisbon',
    'country' => 'Portugal',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1000.0,
    'discount' => 0,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'cover_image' => 'lisbon_apartment.jpg',
    'description' => 'Sunny apartment in downtown Lisbon',
  ),
  30 => 
  array (
    'user_id' => 30,
    'address' => 'Rue Sainte-Catherine 120',
    'city' => 'Bordeaux',
    'country' => 'France',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 0,
    'latitude' => 44.8378,
    'longitude' => -0.5792,
    'cover_image' => 'bordeaux_apartment.jpg',
    'description' => 'Comfortable apartment on popular shopping street',
  ),
  31 => 
  array (
    'user_id' => 31,
    'address' => 'Utrechtsestraat 45',
    'city' => 'Amsterdam',
    'country' => 'Netherlands',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 10,
    'latitude' => 52.3702,
    'longitude' => 4.8952,
    'cover_image' => 'amsterdam_apartment.jpg',
    'description' => 'Charming canal-side apartment in Amsterdam',
  ),
  32 => 
  array (
    'user_id' => 32,
    'address' => 'Plaza Mayor 15',
    'city' => 'Madrid',
    'country' => 'Spain',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 0,
    'latitude' => 40.4168,
    'longitude' => -3.7038,
    'cover_image' => 'madrid_apartment.jpg',
    'description' => 'Spacious apartment on Plaza Mayor',
  ),
  33 => 
  array (
    'user_id' => 33,
    'address' => 'Königsallee 10',
    'city' => 'Dusseldorf',
    'country' => 'Germany',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1600.0,
    'discount' => 10,
    'latitude' => 51.2277,
    'longitude' => 6.7735,
    'cover_image' => 'dusseldorf_apartment.jpg',
    'description' => 'Elegant apartment in central Dusseldorf',
  ),
  34 => 
  array (
    'user_id' => 34,
    'address' => 'Nevsky Prospekt 35',
    'city' => 'Saint Petersburg',
    'country' => 'Russia',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 900.0,
    'discount' => 0,
    'latitude' => 59.9343,
    'longitude' => 30.3351,
    'cover_image' => 'saintpetersburg_apartment2.jpg',
    'description' => 'Centrally located apartment with city view',
  ),
  35 => 
  array (
    'user_id' => 35,
    'address' => 'Via della Moscova 47',
    'city' => 'Milan',
    'country' => 'Italy',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2000.0,
    'discount' => 10,
    'latitude' => 45.4642,
    'longitude' => 9.19,
    'cover_image' => 'milan_apartment.jpg',
    'description' => 'Elegant apartment in the heart of Milan',
  ),
  36 => 
  array (
    'user_id' => 36,
    'address' => 'Voie Georges Pompidou 10',
    'city' => 'Paris',
    'country' => 'France',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2500.0,
    'discount' => 10,
    'latitude' => 48.8566,
    'longitude' => 2.3522,
    'cover_image' => 'paris_apartment.jpg',
    'description' => 'Charming apartment with Seine view',
  ),
  37 => 
  array (
    'user_id' => 37,
    'address' => 'Ilica 50',
    'city' => 'Zagreb',
    'country' => 'Croatia',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 45.815,
    'longitude' => 15.9819,
    'cover_image' => 'zagreb_apartment.jpg',
    'description' => 'Spacious apartment in central Zagreb',
  ),
  38 => 
  array (
    'user_id' => 38,
    'address' => 'Skadarlija 20',
    'city' => 'Belgrade',
    'country' => 'Serbia',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 700.0,
    'discount' => 0,
    'latitude' => 44.7866,
    'longitude' => 20.4489,
    'cover_image' => 'belgrade_apartment2.jpg',
    'description' => 'Vintage apartment in historic district',
  ),
  39 => 
  array (
    'user_id' => 39,
    'address' => 'Av. da Liberdade 50',
    'city' => 'Lisbon',
    'country' => 'Portugal',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 10,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'cover_image' => 'lisbon_apartment2.jpg',
    'description' => 'Bright and cozy apartment in central Lisbon',
  ),
  40 => 
  array (
    'user_id' => 40,
    'address' => 'Jungfernstieg 50',
    'city' => 'Hamburg',
    'country' => 'Germany',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 0,
    'latitude' => 53.5511,
    'longitude' => 9.9937,
    'cover_image' => 'hamburg_apartment.jpg',
    'description' => 'Modern apartment in central Hamburg',
  ),
  41 => 
  array (
    'user_id' => 41,
    'address' => 'Rue du Rhône 70',
    'city' => 'Geneva',
    'country' => 'Switzerland',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2300.0,
    'discount' => 0,
    'latitude' => 46.2044,
    'longitude' => 6.1432,
    'cover_image' => 'geneva_apartment2.jpg',
    'description' => 'Stylish apartment in downtown Geneva',
  ),
  42 => 
  array (
    'user_id' => 42,
    'address' => 'Bulevardul Unirii 10',
    'city' => 'Bucharest',
    'country' => 'Romania',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 900.0,
    'discount' => 0,
    'latitude' => 44.4268,
    'longitude' => 26.1025,
    'cover_image' => 'bucharest_apartment.jpg',
    'description' => 'Bright and spacious apartment in Bucharest',
  ),
  43 => 
  array (
    'user_id' => 43,
    'address' => 'Karl Johans gate 20',
    'city' => 'Oslo',
    'country' => 'Norway',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1600.0,
    'discount' => 0,
    'latitude' => 59.9139,
    'longitude' => 10.7522,
    'cover_image' => 'oslo_apartment.jpg',
    'description' => 'Modern apartment in central Oslo',
  ),
  44 => 
  array (
    'user_id' => 44,
    'address' => 'Na Příkopě 25',
    'city' => 'Prague',
    'country' => 'Czech Republic',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 10,
    'latitude' => 50.0755,
    'longitude' => 14.4378,
    'cover_image' => 'prague_apartment.jpg',
    'description' => 'Central apartment with city view in Prague',
  ),
  45 => 
  array (
    'user_id' => 45,
    'address' => 'Ferhadija 30',
    'city' => 'Sarajevo',
    'country' => 'Bosnia and Herzegovina',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 600.0,
    'discount' => 0,
    'latitude' => 43.8563,
    'longitude' => 18.4131,
    'cover_image' => 'sarajevo_apartment.jpg',
    'description' => 'Charming apartment in the heart of Sarajevo',
  ),
  46 => 
  array (
    'user_id' => 46,
    'address' => 'Nemiga Street 40',
    'city' => 'Minsk',
    'country' => 'Belarus',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 500.0,
    'discount' => 0,
    'latitude' => 53.9045,
    'longitude' => 27.5615,
    'cover_image' => 'minsk_apartment.jpg',
    'description' => 'Comfortable apartment in central Minsk',
  ),
  47 => 
  array (
    'user_id' => 47,
    'address' => 'Mannerheimintie 20',
    'city' => 'Helsinki',
    'country' => 'Finland',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 10,
    'latitude' => 60.1699,
    'longitude' => 24.9384,
    'cover_image' => 'helsinki_apartment.jpg',
    'description' => 'Cozy apartment in downtown Helsinki',
  ),
  48 => 
  array (
    'user_id' => 48,
    'address' => 'Fredrikinkatu 61',
    'city' => 'Helsinki',
    'country' => 'Finland',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 0,
    'latitude' => 60.1699,
    'longitude' => 24.9384,
    'cover_image' => 'helsinki_apartment2.jpg',
    'description' => 'Modern apartment in lively district',
  ),
  49 => 
  array (
    'user_id' => 49,
    'address' => 'Pikk 70',
    'city' => 'Tallinn',
    'country' => 'Estonia',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 59.437,
    'longitude' => 24.7536,
    'cover_image' => 'tallinn_apartment.jpg',
    'description' => 'Charming apartment in historic Tallinn',
  ),
  50 => 
  array (
    'user_id' => 50,
    'address' => 'Rue du Marché 30',
    'city' => 'Luxembourg',
    'country' => 'Luxembourg',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2200.0,
    'discount' => 10,
    'latitude' => 49.6116,
    'longitude' => 6.1319,
    'cover_image' => 'luxembourg_apartment.jpg',
    'description' => 'Luxury apartment in central Luxembourg',
  ),
  51 => 
  array (
    'user_id' => 51,
    'address' => 'Bulevar kneza Aleksandra 50',
    'city' => 'Belgrade',
    'country' => 'Serbia',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 700.0,
    'discount' => 0,
    'latitude' => 44.7866,
    'longitude' => 20.4489,
    'cover_image' => 'belgrade_apartment3.jpg',
    'description' => 'Bright and spacious apartment in Belgrade',
  ),
  52 => 
  array (
    'user_id' => 52,
    'address' => 'Calle de Alcalá 70',
    'city' => 'Madrid',
    'country' => 'Spain',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 40.4168,
    'longitude' => -3.7038,
    'cover_image' => 'madrid_apartment2.jpg',
    'description' => 'Elegant apartment in central Madrid',
  ),
  53 => 
  array (
    'user_id' => 53,
    'address' => 'Calle del Arenal 30',
    'city' => 'Madrid',
    'country' => 'Spain',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 0,
    'latitude' => 40.4168,
    'longitude' => -3.7038,
    'cover_image' => 'madrid_apartment3.jpg',
    'description' => 'Cozy apartment in lively Madrid district',
  ),
  54 => 
  array (
    'user_id' => 54,
    'address' => 'Kurfürstendamm 70',
    'city' => 'Berlin',
    'country' => 'Germany',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 52.52,
    'longitude' => 13.405,
    'cover_image' => 'berlin_apartment2.jpg',
    'description' => 'Stylish apartment in central Berlin',
  ),
  55 => 
  array (
    'user_id' => 55,
    'address' => 'Ulitsa Tverskaya 30',
    'city' => 'Moscow',
    'country' => 'Russia',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 2000.0,
    'discount' => 0,
    'latitude' => 55.7558,
    'longitude' => 37.6176,
    'cover_image' => 'moscow_apartment.jpg',
    'description' => 'Spacious apartment in downtown Moscow',
  ),
  56 => 
  array (
    'user_id' => 56,
    'address' => 'Rue du Faubourg Saint-Honoré 70',
    'city' => 'Paris',
    'country' => 'France',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2600.0,
    'discount' => 10,
    'latitude' => 48.8566,
    'longitude' => 2.3522,
    'cover_image' => 'paris_apartment2.jpg',
    'description' => 'Luxury apartment in central Paris',
  ),
  57 => 
  array (
    'user_id' => 57,
    'address' => 'Strøget 40',
    'city' => 'Copenhagen',
    'country' => 'Denmark',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 0,
    'latitude' => 55.6761,
    'longitude' => 12.5683,
    'cover_image' => 'copenhagen_apartment.jpg',
    'description' => 'Modern apartment in downtown Copenhagen',
  ),
  58 => 
  array (
    'user_id' => 58,
    'address' => 'Váci utca 20',
    'city' => 'Budapest',
    'country' => 'Hungary',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 47.4979,
    'longitude' => 19.0402,
    'cover_image' => 'budapest_apartment.jpg',
    'description' => 'Comfortable apartment in central Budapest',
  ),
  59 => 
  array (
    'user_id' => 59,
    'address' => 'Avinguda del Paral·lel 50',
    'city' => 'Barcelona',
    'country' => 'Spain',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 10,
    'latitude' => 41.3851,
    'longitude' => 2.1734,
    'cover_image' => 'barcelona_apartment.jpg',
    'description' => 'Bright apartment in vibrant Barcelona',
  ),
  60 => 
  array (
    'user_id' => 60,
    'address' => 'Kings Road 100',
    'city' => 'London',
    'country' => 'United Kingdom',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 2600.0,
    'discount' => 0,
    'latitude' => 51.5074,
    'longitude' => -0.1278,
    'cover_image' => 'london_apartment2.jpg',
    'description' => 'Spacious apartment in fashionable London area',
  ),
  61 => 
  array (
    'user_id' => 61,
    'address' => 'Via del Corso 70',
    'city' => 'Rome',
    'country' => 'Italy',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 10,
    'latitude' => 41.9028,
    'longitude' => 12.4964,
    'cover_image' => 'rome_apartment2.jpg',
    'description' => 'Stylish apartment in the heart of Rome',
  ),
  62 => 
  array (
    'user_id' => 62,
    'address' => 'Plaza Mayor 20',
    'city' => 'Madrid',
    'country' => 'Spain',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 0,
    'latitude' => 40.4168,
    'longitude' => -3.7038,
    'cover_image' => 'madrid_apartment4.jpg',
    'description' => 'Charming apartment in central Madrid',
  ),
  63 => 
  array (
    'user_id' => 63,
    'address' => 'Herengracht 50',
    'city' => 'Amsterdam',
    'country' => 'Netherlands',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2000.0,
    'discount' => 0,
    'latitude' => 52.3667,
    'longitude' => 4.8945,
    'cover_image' => 'amsterdam_apartment2.jpg',
    'description' => 'Beautiful canal-side apartment in Amsterdam',
  ),
  64 => 
  array (
    'user_id' => 64,
    'address' => 'Platz der Republik 1',
    'city' => 'Berlin',
    'country' => 'Germany',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 10,
    'latitude' => 52.5186,
    'longitude' => 13.4083,
    'cover_image' => 'berlin_apartment3.jpg',
    'description' => 'Comfortable apartment in vibrant Berlin district',
  ),
  65 => 
  array (
    'user_id' => 65,
    'address' => 'Avenue des Champs-Élysées 50',
    'city' => 'Paris',
    'country' => 'France',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2700.0,
    'discount' => 0,
    'latitude' => 48.8566,
    'longitude' => 2.3522,
    'cover_image' => 'paris_apartment3.jpg',
    'description' => 'Stylish apartment on famous Parisian avenue',
  ),
  66 => 
  array (
    'user_id' => 66,
    'address' => 'Bahnhofstrasse 30',
    'city' => 'Zurich',
    'country' => 'Switzerland',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2800.0,
    'discount' => 10,
    'latitude' => 47.3769,
    'longitude' => 8.5417,
    'cover_image' => 'zurich_apartment.jpg',
    'description' => 'Luxurious apartment in the heart of Zurich',
  ),
  67 => 
  array (
    'user_id' => 67,
    'address' => 'Akersgata 55',
    'city' => 'Oslo',
    'country' => 'Norway',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2000.0,
    'discount' => 0,
    'latitude' => 59.9139,
    'longitude' => 10.7522,
    'cover_image' => 'oslo_apartment.jpg',
    'description' => 'Bright and modern apartment in central Oslo',
  ),
  68 => 
  array (
    'user_id' => 68,
    'address' => 'Rue de la Loi 100',
    'city' => 'Brussels',
    'country' => 'Belgium',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 50.8503,
    'longitude' => 4.3517,
    'cover_image' => 'brussels_apartment.jpg',
    'description' => 'Cozy apartment in bustling Brussels',
  ),
  69 => 
  array (
    'user_id' => 69,
    'address' => 'Boulevard Haussmann 150',
    'city' => 'Paris',
    'country' => 'France',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 3000.0,
    'discount' => 0,
    'latitude' => 48.8738,
    'longitude' => 2.3292,
    'cover_image' => 'paris_apartment4.jpg',
    'description' => 'Stunning apartment in upscale Paris area',
  ),
  70 => 
  array (
    'user_id' => 70,
    'address' => 'Mannerheimintie 30',
    'city' => 'Helsinki',
    'country' => 'Finland',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 60.1756,
    'longitude' => 24.9342,
    'cover_image' => 'helsinki_apartment.jpg',
    'description' => 'Comfortable apartment in the heart of Helsinki',
  ),
  71 => 
  array (
    'user_id' => 71,
    'address' => 'Strandvägen 20',
    'city' => 'Stockholm',
    'country' => 'Sweden',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2000.0,
    'discount' => 0,
    'latitude' => 59.3293,
    'longitude' => 18.0686,
    'cover_image' => 'stockholm_apartment.jpg',
    'description' => 'Stylish apartment in exclusive Stockholm area',
  ),
  72 => 
  array (
    'user_id' => 72,
    'address' => 'Hofgasse 10',
    'city' => 'Vienna',
    'country' => 'Austria',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 0,
    'latitude' => 48.2082,
    'longitude' => 16.3738,
    'cover_image' => 'vienna_apartment.jpg',
    'description' => 'Elegant apartment in historic Vienna',
  ),
  73 => 
  array (
    'user_id' => 73,
    'address' => 'Friedrichstraße 100',
    'city' => 'Berlin',
    'country' => 'Germany',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 52.52,
    'longitude' => 13.405,
    'cover_image' => 'berlin_apartment4.jpg',
    'description' => 'Charming apartment in central Berlin',
  ),
  74 => 
  array (
    'user_id' => 74,
    'address' => 'Jægersborggade 51',
    'city' => 'Copenhagen',
    'country' => 'Denmark',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1900.0,
    'discount' => 10,
    'latitude' => 55.6784,
    'longitude' => 12.5692,
    'cover_image' => 'copenhagen_apartment2.jpg',
    'description' => 'Cosy apartment in the hipster district of Copenhagen',
  ),
  75 => 
  array (
    'user_id' => 75,
    'address' => 'Długa 70',
    'city' => 'Warsaw',
    'country' => 'Poland',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 800.0,
    'discount' => 0,
    'latitude' => 52.2297,
    'longitude' => 21.0122,
    'cover_image' => 'warsaw_apartment.jpg',
    'description' => 'Spacious apartment in historic Warsaw',
  ),
  76 => 
  array (
    'user_id' => 76,
    'address' => 'Stadiou 30',
    'city' => 'Athens',
    'country' => 'Greece',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 700.0,
    'discount' => 10,
    'latitude' => 37.9838,
    'longitude' => 23.7275,
    'cover_image' => 'athens_apartment.jpg',
    'description' => 'Sunny apartment in the heart of Athens',
  ),
  77 => 
  array (
    'user_id' => 77,
    'address' => 'Avenida de América 40',
    'city' => 'Madrid',
    'country' => 'Spain',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 0,
    'latitude' => 40.4193,
    'longitude' => -3.7004,
    'cover_image' => 'madrid_apartment2.jpg',
    'description' => 'Modern apartment in vibrant Madrid',
  ),
  78 => 
  array (
    'user_id' => 78,
    'address' => 'Kalevankatu 40',
    'city' => 'Helsinki',
    'country' => 'Finland',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 60.1756,
    'longitude' => 24.9341,
    'cover_image' => 'helsinki_apartment2.jpg',
    'description' => 'Cozy apartment in central Helsinki',
  ),
  79 => 
  array (
    'user_id' => 79,
    'address' => 'Rue Royale 100',
    'city' => 'Brussels',
    'country' => 'Belgium',
    'square_meters' => 90,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 1600.0,
    'discount' => 0,
    'latitude' => 50.8466,
    'longitude' => 4.3528,
    'cover_image' => 'brussels_apartment2.jpg',
    'description' => 'Elegant apartment in bustling Brussels',
  ),
  80 => 
  array (
    'user_id' => 80,
    'address' => 'Karavannaya ulitsa 20',
    'city' => 'Saint Petersburg',
    'country' => 'Russia',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 10,
    'latitude' => 59.9343,
    'longitude' => 30.3351,
    'cover_image' => 'saintpetersburg_apartment.jpg',
    'description' => 'Stylish apartment in the heart of Saint Petersburg',
  ),
  81 => 
  array (
    'user_id' => 81,
    'address' => 'Wenceslas Square 40',
    'city' => 'Prague',
    'country' => 'Czech Republic',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 0,
    'latitude' => 50.0755,
    'longitude' => 14.4378,
    'cover_image' => 'prague_apartment.jpg',
    'description' => 'Charming apartment in historic Prague',
  ),
  82 => 
  array (
    'user_id' => 82,
    'address' => 'Stroget 30',
    'city' => 'Copenhagen',
    'country' => 'Denmark',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 10,
    'latitude' => 55.6761,
    'longitude' => 12.5683,
    'cover_image' => 'copenhagen_apartment3.jpg',
    'description' => 'Bright and airy apartment in central Copenhagen',
  ),
  83 => 
  array (
    'user_id' => 83,
    'address' => 'Ermou 70',
    'city' => 'Athens',
    'country' => 'Greece',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 700.0,
    'discount' => 0,
    'latitude' => 37.9753,
    'longitude' => 23.736,
    'cover_image' => 'athens_apartment2.jpg',
    'description' => 'Modern apartment in the vibrant city of Athens',
  ),
  84 => 
  array (
    'user_id' => 84,
    'address' => 'Strada Nuova 60',
    'city' => 'Venice',
    'country' => 'Italy',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 5,
    'latitude' => 45.4408,
    'longitude' => 12.3155,
    'cover_image' => 'venice_apartment.jpg',
    'description' => 'Charming and cosy apartment in the heart of Venice',
  ),
  85 => 
  array (
    'user_id' => 85,
    'address' => 'Königsstraße 30',
    'city' => 'Stuttgart',
    'country' => 'Germany',
    'square_meters' => 85,
    'bathrooms' => 1,
    'rooms' => 3,
    'price' => 1600.0,
    'discount' => 10,
    'latitude' => 48.7758,
    'longitude' => 9.1829,
    'cover_image' => 'stuttgart_apartment.jpg',
    'description' => 'Spacious and bright apartment in Stuttgart center',
  ),
  86 => 
  array (
    'user_id' => 86,
    'address' => 'Grafton Street 40',
    'city' => 'Dublin',
    'country' => 'Ireland',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 0,
    'latitude' => 53.3498,
    'longitude' => -6.2603,
    'cover_image' => 'dublin_apartment.jpg',
    'description' => 'Stylish and comfortable apartment in Dublin city',
  ),
  87 => 
  array (
    'user_id' => 87,
    'address' => 'Marnixstraat 100',
    'city' => 'Amsterdam',
    'country' => 'Netherlands',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2000.0,
    'discount' => 10,
    'latitude' => 52.3702,
    'longitude' => 4.8952,
    'cover_image' => 'amsterdam_apartment.jpg',
    'description' => 'Modern apartment in vibrant Amsterdam',
  ),
  88 => 
  array (
    'user_id' => 88,
    'address' => 'Rue des Saints-Pères 60',
    'city' => 'Paris',
    'country' => 'France',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2500.0,
    'discount' => 0,
    'latitude' => 48.8566,
    'longitude' => 2.3522,
    'cover_image' => 'paris_apartment5.jpg',
    'description' => 'Elegant apartment in historic Parisian district',
  ),
  89 => 
  array (
    'user_id' => 89,
    'address' => 'Götgatan 40',
    'city' => 'Stockholm',
    'country' => 'Sweden',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 0,
    'latitude' => 59.3293,
    'longitude' => 18.0686,
    'cover_image' => 'stockholm_apartment2.jpg',
    'description' => 'Cosy apartment in trendy Stockholm area',
  ),
  90 => 
  array (
    'user_id' => 90,
    'address' => 'Alser Straße 50',
    'city' => 'Vienna',
    'country' => 'Austria',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1300.0,
    'discount' => 0,
    'latitude' => 48.2082,
    'longitude' => 16.3738,
    'cover_image' => 'vienna_apartment2.jpg',
    'description' => 'Spacious apartment in classic Vienna',
  ),
  91 => 
  array (
    'user_id' => 91,
    'address' => 'Oranienburger Straße 70',
    'city' => 'Berlin',
    'country' => 'Germany',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 5,
    'latitude' => 52.52,
    'longitude' => 13.405,
    'cover_image' => 'berlin_apartment5.jpg',
    'description' => 'Bright apartment in central Berlin district',
  ),
  92 => 
  array (
    'user_id' => 92,
    'address' => 'Kammakargatan 40',
    'city' => 'Stockholm',
    'country' => 'Sweden',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 0,
    'latitude' => 59.3345,
    'longitude' => 18.0632,
    'cover_image' => 'stockholm_apartment3.jpg',
    'description' => 'Chic apartment in vibrant Stockholm neighborhood',
  ),
  93 => 
  array (
    'user_id' => 93,
    'address' => 'Rua Garrett 100',
    'city' => 'Lisbon',
    'country' => 'Portugal',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1100.0,
    'discount' => 5,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'cover_image' => 'lisbon_apartment.jpg',
    'description' => 'Beautiful apartment in Lisbon\'s historical center',
  ),
  94 => 
  array (
    'user_id' => 94,
    'address' => 'Calle Serrano 80',
    'city' => 'Madrid',
    'country' => 'Spain',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1500.0,
    'discount' => 10,
    'latitude' => 40.4361,
    'longitude' => -3.6868,
    'cover_image' => 'madrid_apartment3.jpg',
    'description' => 'Stylish apartment in upscale Madrid neighborhood',
  ),
  95 => 
  array (
    'user_id' => 95,
    'address' => 'Piazza del Campo 60',
    'city' => 'Siena',
    'country' => 'Italy',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1200.0,
    'discount' => 5,
    'latitude' => 43.3186,
    'longitude' => 11.3314,
    'cover_image' => 'siena_apartment.jpg',
    'description' => 'Cozy apartment with a view of Piazza del Campo in Siena',
  ),
  96 => 
  array (
    'user_id' => 96,
    'address' => 'Avenida da Liberdade 100',
    'city' => 'Lisbon',
    'country' => 'Portugal',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 0,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'cover_image' => 'lisbon_apartment2.jpg',
    'description' => 'Modern apartment on Avenida da Liberdade in Lisbon',
  ),
  97 => 
  array (
    'user_id' => 97,
    'address' => 'Karl Johans gate 70',
    'city' => 'Oslo',
    'country' => 'Norway',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2200.0,
    'discount' => 10,
    'latitude' => 59.9139,
    'longitude' => 10.7522,
    'cover_image' => 'oslo_apartment2.jpg',
    'description' => 'Luxurious apartment on Karl Johans gate in Oslo',
  ),
  98 => 
  array (
    'user_id' => 98,
    'address' => 'Borgo Pinti 60',
    'city' => 'Florence',
    'country' => 'Italy',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1400.0,
    'discount' => 0,
    'latitude' => 43.7764,
    'longitude' => 11.257,
    'cover_image' => 'florence_apartment.jpg',
    'description' => 'Charming apartment in the historic center of Florence',
  ),
  99 => 
  array (
    'user_id' => 99,
    'address' => 'Paseo de Gracia 100',
    'city' => 'Barcelona',
    'country' => 'Spain',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2500.0,
    'discount' => 0,
    'latitude' => 41.3933,
    'longitude' => 2.1638,
    'cover_image' => 'barcelona_apartment2.jpg',
    'description' => 'Luxury apartment on Paseo de Gracia in Barcelona',
  ),
  100 => 
  array (
    'user_id' => 100,
    'address' => 'Oudezijds Voorburgwal 40',
    'city' => 'Amsterdam',
    'country' => 'Netherlands',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2000.0,
    'discount' => 10,
    'latitude' => 52.3721,
    'longitude' => 4.8986,
    'cover_image' => 'amsterdam_apartment3.jpg',
    'description' => 'Historic apartment on Oudezijds Voorburgwal in Amsterdam',
  ),
  101 => 
  array (
    'user_id' => 101,
    'address' => 'Oxford Street 80',
    'city' => 'London',
    'country' => 'United Kingdom',
    'square_meters' => 80,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 2800.0,
    'discount' => 0,
    'latitude' => 51.5154,
    'longitude' => -0.1412,
    'cover_image' => 'london_apartment3.jpg',
    'description' => 'Modern apartment on Oxford Street in London',
  ),
  102 => 
  array (
    'user_id' => 102,
    'address' => 'Gamla Stan 50',
    'city' => 'Stockholm',
    'country' => 'Sweden',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1900.0,
    'discount' => 5,
    'latitude' => 59.3257,
    'longitude' => 18.0719,
    'cover_image' => 'stockholm_apartment4.jpg',
    'description' => 'Cosy apartment in the charming Gamla Stan of Stockholm',
  ),
  103 => 
  array (
    'user_id' => 103,
    'address' => 'Avenida da Liberdade 150',
    'city' => 'Lisbon',
    'country' => 'Portugal',
    'square_meters' => 75,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1600.0,
    'discount' => 0,
    'latitude' => 38.7223,
    'longitude' => -9.1393,
    'cover_image' => 'lisbon_apartment3.jpg',
    'description' => 'Elegant apartment on Avenida da Liberdade in Lisbon',
  ),
  104 => 
  array (
    'user_id' => 104,
    'address' => 'Storgatan 70',
    'city' => 'Stockholm',
    'country' => 'Sweden',
    'square_meters' => 70,
    'bathrooms' => 1,
    'rooms' => 2,
    'price' => 1800.0,
    'discount' => 10,
    'latitude' => 59.3327,
    'longitude' => 18.0632,
    'cover_image' => 'stockholm_apartment5.jpg',
    'description' => 'Bright and modern apartment in central Stockholm',
  ),
);

?>